module.exports = {
    ERROR_MESSAGE: {
        USER: {
            USER_ERROR: 'USER_ERROR',
            USER_NOT_FOUND: 'USER_NOT_FOUND',
            USER_EXIST: 'USER_EXIST',
            EMAIL_EXIST: 'EMAIL_EXIST',
            EMAIL_INVALID: 'EMAIL_INVALID',
            EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND', 
            EMAIL_ERROR:'EMAIL_ERROR',
            PASS_WRONG: 'PASS_WRONG', // Báo lỗi: 2.a.1
            IMAGE_USER_NOT_FOUND:'IMAGE_USER_NOT_FOUND',
            USER_REGISTERED:'USER_REGISTERED',
            USER_NOT_OUT:'USER_NOT_OUT_PARTY',
            USER_INVITED:'USER_INVITED',
            USER_MAX:'USER_MAX'
            
        },
        TYPE_FOOD:{
            TYPE_FOOD_NOT_FOUND: 'TYPE_FOOD_NOT_FOUND',
            TYOE_FOOD_IS_EXIST:'TYOE_FOOD_IS_EXIST'
        },
        RESTAURANT:{
            RESTAURANT_NOT_FOUND:'RESTAURANT_NOT_FOUND',
            RESTAURANT_IS_VALID:'RESTAURANT_IS_VALID',
            RESTAURANT_IS_EXITS:'RESTAURANT_IS_EXITS',
            RESTAURANT_NAME_IS_REQUIRED: 'RESTAURANT_NAME_IS_REQUIRED',
            IMAGE_ERROR:'IMAGE_ERROR'
        },
        PARTY:{
            PARTY_NOT_FOUND:'PARTY_NOT_FOUND',
            PARTY_IS_VALID:'PARTY_IS_VALID',
            PARTY_DATE_ERROR:'PARTY_DATE_ERROR',
            PARTY_ALREADY_FULL:'PARTY_ALREADY_FULL' ,
            PARTY_PRIVATE:'PARTY_PRIVATE'

        },
        AUTH: {
            INVALID_TOKEN: 'INVALID_TOKEN',
            PERMISSION: 'PERMISSION',
            NOT_AUTHORIZED: 'NOT_AUTHORIZED'
          }
    },
    SUCCESS_MESSAGE: {
        USER: {
            CREATED: 'USER_CREATE',
            DELETED: 'USER_DELETE',
            SUCCES: 'SUCCES',
            SENT_MAIL:'SENT_MAIL_SUCCESSFULLY',
            USER_WAS_A_MAKE_FRIEND:'USER_WAS_A_MAKE_FRIEND',
            MAKE_FRIEND_SUCCES:'MAKE_FRIEND_SUCCES',
            USER_FRIEND_NOT_FOUND:'USER_FRIEND_NOT_FOUND',
            USER_AVATAR_UPDATED:'USER_AVATAR_UPDATED',
            USER_FRIEND_DELETED:'USER_FRIEND_DELETED',
            LOGIN_SUCCESS: 'LOGIN_SUCCESS',
            SIGNUP_SUCCES: 'SIGN_UP_SUCCESS'
        },
        TYPE_FOOD:{
            TYPE_FOOD_CREATED: 'TYPE_FOOD_CREATED',
            TYPE_FOOD_DELETED: 'TYPE_FOOD_DELETED',
        },
        RESTAURANT:{
            RESTAURANT_FOOD_CREATED: 'RESTAURANT_CREATED',
            RESTAURANT_FOOD_UPDATED: 'RESTAURANT_UPDATED',
            RESTAURANT_FOOD_DELETED: 'RESTAURANT_DELETED',
            RESTAURANT_FOOD_UPDATED_IMAGE: 'RESTAURANT_UPDATED_IMAGE',
        },
        PARTY:{
            PARTY_FOOD_CREATED: 'PARTY_CREATED',
            PARTY_FOOD_DELETED: 'PARTY_DELETED'
        }
    },
    STATUS_CODE: {
        SUCCES: 200,
        CREATED: 201,
        ACCEPTED: 202,
        NOT_FOUND: 404,
        ERROR: 400,
        ERROR_SERVER: 500
    }
}